[build]
  functions = "functions"

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
